sfe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000
title:  h2ero's blog
author:  h2ero


markdown:    rdiscount
permalink: /:categories/:month-:day-:year/:title.html
pygments: true
paginate: 16


rdiscount:
  extensions: []

