#!/bin/bash
#文章名称
name=$1
#今日日期
date=$(date +"%Y-%m-%d")
#PATH
DIR="/media/S/blog/_posts/"
echo DIR
#md文件全名
blog="${date}-${name}".md
#文件夹名称
YEAR=$(date +"%Y")
#判断文件夹存在否
if [ -d $DIR$YEAR ];then
	cp ${DIR}tpl.md $DIR$YEAR/$blog
else
	mkdir $DIR$YEAR
	cp ${DIR}tpl.md $DIR$YEAR/$blog
fi
echo $DIR$YEAR/$blog
echo $blog" have created!"
vim $DIR$YEAR/$blog
